import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TabManagerProvider } from "@/api/publicTabManager";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    // Disable darkreader
    "darkreader-lock": "true",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TabManagerProvider>
          <Provider>{children}</Provider>
        </TabManagerProvider>
      </body>
    </html>
  );
}
